use klem::{LemmaKind, Lemmatizer};

#[test]
fn curated_dictionary_forms() {
    let engine = Lemmatizer::new();
    // Independently specified spelling examples; not generated by the engine.
    for (word, expected) in [
        ("먹다", "먹다"),
        ("먹고", "먹다"),
        ("먹었어요", "먹다"),
        ("갔어요", "가다"),
        ("가셨어요", "가다"),
        ("먹었었어요", "먹다"),
        ("먹으셨겠어요", "먹다"),
        ("먹더라", "먹다"),
        ("먹습니다", "먹다"),
        ("갑니다", "가다"),
        ("삽니다", "살다"),
        ("사는", "살다"),
        ("살면", "살다"),
        ("사세요", "살다"),
        ("간", "가다"),
        ("갈", "가다"),
        ("먹은", "먹다"),
        ("먹을", "먹다"),
        ("먹음", "먹다"),
        ("삶", "살다"),
        ("앎", "알다"),
        ("한다는", "하다"),
        ("아니에요", "아니다"),
        ("아닌가", "아니다"),
        ("있는가를", "있다"),
        ("10시까지만", "10시"),
        ("학교까지의", "학교"),
        ("상품으로서의", "상품"),
        ("게", "것"),
        ("게", "거"),
        ("감", "가다"),
        ("가는", "가다"),
        ("간다", "가다"),
        ("듣고", "듣다"),
        ("들어", "듣다"),
        ("들으면", "듣다"),
        ("들은", "듣다"),
        ("추워요", "춥다"),
        ("추우면", "춥다"),
        ("추운", "춥다"),
        ("도와요", "돕다"),
        ("고와", "곱다"),
        ("돕습니다", "돕다"),
        ("지어요", "짓다"),
        ("지으면", "짓다"),
        ("지은", "짓다"),
        ("빨개요", "빨갛다"),
        ("빨간", "빨갛다"),
        ("그래요", "그렇다"),
        ("그러면", "그렇다"),
        ("몰라요", "모르다"),
        ("불러요", "부르다"),
        ("이르러", "이르다"),
        ("아파요", "아프다"),
        ("써요", "쓰다"),
        ("커요", "크다"),
        ("퍼요", "푸다"),
        ("봐요", "보다"),
        ("줘요", "주다"),
        ("돼요", "되다"),
        ("마셔요", "마시다"),
        ("했어요", "하다"),
        ("하였어요", "하다"),
        ("공부했어요", "공부하다"),
        ("놓아", "놓다"),
        ("좋아", "좋다"),
        ("벗어", "벗다"),
        ("믿어", "믿다"),
        ("학교에서", "학교"),
        ("학교에서는", "학교"),
        ("학교에서만은", "학교"),
        ("사람만으로도", "사람"),
        ("책으로", "책"),
        ("길로", "길"),
        ("서울의", "서울"),
        ("도서관에서", "도서관"),
        ("오간수다리에는", "오간수다리"),
        ("내가", "나"),
        ("제가", "저"),
        ("누가", "누구"),
        ("내", "나"),
        ("먹기를", "먹다"),
        ("먹음은", "먹다"),
    ] {
        let result = engine.analyze_word(word).unwrap();
        assert!(
            result.lemma_strings().contains(&expected),
            "{word} missing {expected}: {:?}",
            result.lemma_strings()
        );
    }
}

#[test]
fn alternatives_and_grouping() {
    let e = Lemmatizer::new();
    for (word, components) in [
        ("학생입니다", vec!["학생", "이다"]),
        ("학생이에요", vec!["학생", "이다"]),
        ("의사예요", vec!["의사", "이다"]),
        ("학생이고싶다", vec!["학생", "이다", "싶다"]),
        ("먹어봄을", vec!["먹다", "보다"]),
        ("것임을", vec!["것", "이다"]),
        ("2년만이다", vec!["2년", "이다"]),
        ("학생이었다", vec!["학생", "이다"]),
        ("의사였다", vec!["의사", "이다"]),
        ("의사다", vec!["의사", "이다"]),
        ("학생이라고", vec!["학생", "이다"]),
        ("의사라는", vec!["의사", "이다"]),
        ("먹어봤어요", vec!["먹다", "보다"]),
        ("먹고있다", vec!["먹다", "있다"]),
        ("하지않았다", vec!["하다", "않다"]),
        ("먹어보고있다", vec!["먹다", "보다", "있다"]),
    ] {
        let r = e.analyze_word(word).unwrap();
        assert!(
            r.analyses.iter().any(
                |a| a.lemmas.iter().map(|l| l.text.as_str()).collect::<Vec<_>>() == components
            ),
            "missing grouped {components:?} for {word}"
        );
    }
    let r = e.analyze_word("들어").unwrap();
    for candidate in ["들다", "듣다"] {
        assert!(r.lemma_strings().contains(&candidate));
    }
    let r = e.analyze_word("나는").unwrap();
    for candidate in ["나", "날다", "나다"] {
        assert!(r.lemma_strings().contains(&candidate));
    }
}

#[test]
fn invalid_boundaries_do_not_apply() {
    let e = Lemmatizer::new();
    for (surface, invalid) in [
        ("먹ㅂ니다", "먹다"),
        ("먹니다", "먹다"),
        ("가습니다", "가다"),
        ("먹면", "먹다"),
        ("먹아", "먹다"),
        ("잡어", "잡다"),
        ("살습니다", "살다"),
        ("살세요", "살다"),
        ("추웁니다", "춥다"),
        ("먹겠었어요", "먹다"),
        ("하아", "하다"),
        ("하어", "하다"),
        ("감", "갈다"),
    ] {
        assert!(
            !e.analyze_word(surface)
                .unwrap()
                .lemma_strings()
                .contains(&invalid),
            "invalid recovery {surface} -> {invalid}"
        );
    }
    for (surface, invalid) in [
        ("학교은", "학교"),
        ("책는", "책"),
        ("길으로", "길"),
        ("책로", "책"),
        ("학교는은", "학교"),
    ] {
        assert!(
            !e.analyze_word(surface).unwrap().analyses.iter().any(|a| a
                .lemmas
                .iter()
                .any(|l| l.kind == LemmaKind::Nominal && l.text == invalid)),
            "invalid particle {surface}"
        );
    }
}

#[test]
fn explanations_determinism_and_filtering() {
    let e = Lemmatizer::new();
    for word in [
        "먹으셨겠어요",
        "먹어보고있다",
        "학교에서는",
        "그래요",
        "학생이라고",
        "의사라서",
        "아니라서",
    ] {
        let first = e.analyze_word(word).unwrap();
        assert_eq!(first, e.analyze_word(word).unwrap());
        for a in &first.analyses {
            for id in &a.rules {
                assert!(klem::rule_explanation(id).is_some(), "{id}");
            }
        }
        assert!(
            first
                .filtered(|l| l.text == "먹다")
                .analyses
                .iter()
                .all(|a| a.lemmas.iter().all(|l| l.text == "먹다"))
        );
    }
}
