"""Generate finite semantic formations and verify the real-importer source adapter."""

import argparse
import json

from continuation_inflection_audit import project_lmf
from doeda_native_preflight import words
from doeda_originless_audit import FIXTURE
from doeda_originless_audit import REPORT as PREFLIGHT
from lexical_nada_audit import ROOT, read, sha
from native_lmf import verify_native_lmf

MODULE = ROOT / "src/doeda_originless_forms.rs"
LMF = ROOT / "tests/fixtures/krdict-doeda-originless.json"
PROVENANCE = ROOT / "tests/fixtures/doeda-originless-import.json"
REGRESSIONS = ROOT / "tests/fixtures/doeda-originless-before.json"
SUPPLEMENT = ROOT / "tests/fixtures/doeda-partial-origin-sources.json"


def module_text():
    original = read(FIXTURE)["formations"]
    supplemental = read(SUPPLEMENT)["formations"]
    assert len(original) == 17 and len(supplemental) == 2
    forms = sorted(original + supplemental, key=lambda f: f["base"])
    assert len(forms) == len({f["base"] for f in forms}) == 19
    rows = []
    for f in forms:
        assert f["head"] == f["base"] + "되다"
        assert (f["base_kind"], f["predicate_class"], f["origin_relation"]) == (
            "nominal",
            "verb",
            "unknown",
        )
        entries = json.dumps(f["whole_entries"], ensure_ascii=False)
        origins = json.dumps(f.get("expected_origins", []), ensure_ascii=False)
        complete = str(f.get("whole_origins_complete", False)).lower()
        rows.append(
            "    OriginSource {\n"
            f'        base: "{f["base"]}",\n'
            f"        expected_origins: &{origins},\n"
            f"        whole_entries: &{entries},\n"
            f"        whole_origins_complete: {complete},\n"
            "    },"
        )
    return (
        "//! Finite native noun/verb semantic links; missing origins remain unknown.\n"
        "//! Generated by tools/doeda_originless_implementation.py for COV-022m.\n"
        "use crate::doeda_identity::OriginSource;\n\n"
        "pub(crate) fn source(base: &str) -> Option<&'static OriginSource> {\n"
        "    SOURCES\n"
        "        .binary_search_by_key(&base, |s| s.base)\n"
        "        .ok()\n"
        "        .map(|i| &SOURCES[i])\n"
        "}\n\n"
        "const SOURCES: &[OriginSource] = &[\n" + "\n".join(rows) + "\n];\n"
    )


def generate():
    assert not any(p.exists() for p in (MODULE, LMF, PROVENANCE, REGRESSIONS))
    preflight = read(PREFLIGHT)
    native = preflight["complete_native_entries"]
    projected, hashes = project_lmf(native)
    lmf = {"LexicalResource": {"Lexicon": {"LexicalEntry": list(projected.values())}}}
    verify_native_lmf(lmf, native)
    LMF.write_text(json.dumps(lmf, ensure_ascii=False, separators=(",", ":")) + "\n")
    MODULE.write_text(module_text())
    REGRESSIONS.write_text(
        json.dumps(
            {
                "preflight_sha256": sha(PREFLIGHT),
                "before_words": words(preflight["before_streams"]["raw"]),
                "corpus_occurrences": preflight["corpus_occurrences"],
            },
            ensure_ascii=False,
            separators=(",", ":"),
        )
        + "\n"
    )
    PROVENANCE.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "preflight_sha256": sha(PREFLIGHT),
                "fixture_sha256": sha(FIXTURE),
                "lmf_sha256": sha(LMF),
                "regressions_sha256": sha(REGRESSIONS),
                "source_files_sha256": hashes,
                "native_entries": len(native),
                "projection": "Full native entries with English translations; other languages preserved in immutable source preflight. NIKL Korean Basic Dictionary CC BY-SA 2.0 KR.",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n"
    )
    verify()


def verify():
    p = read(PROVENANCE)
    assert p["schema_version"] == 1
    assert p["preflight_sha256"] == sha(PREFLIGHT)
    assert p["fixture_sha256"] == sha(FIXTURE)
    assert p["lmf_sha256"] == sha(LMF)
    assert p["regressions_sha256"] == sha(REGRESSIONS)
    assert MODULE.read_text() == module_text()
    native = read(PREFLIGHT)["complete_native_entries"]
    assert p["native_entries"] == len(native)
    preflight = read(PREFLIGHT)
    assert read(REGRESSIONS) == {
        "preflight_sha256": sha(PREFLIGHT),
        "before_words": words(preflight["before_streams"]["raw"]),
        "corpus_occurrences": preflight["corpus_occurrences"],
    }
    verify_native_lmf(read(LMF), native)
    for path, digest in p["source_files_sha256"].items():
        if (ROOT / path).exists():
            assert sha(ROOT / path) == digest
    print(
        "Verified 17 original and 2 supplemental semantic formations, unknown noun origins and",
        len(native),
        "native importer entries.",
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--generate", action="store_true")
    group.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    generate() if args.generate else verify()
