"""Build and verify the finite native noun-origin formation table and importer."""

import argparse
import json

from continuation_inflection_audit import project_lmf
from doeda_native_audit import FIXTURE
from doeda_native_preflight import REPORT as PREFLIGHT
from lexical_nada_audit import ROOT, read, sha
from native_lmf import verify_native_lmf

MODULE = ROOT / "src/doeda_native_forms.rs"
LMF = ROOT / "tests/fixtures/krdict-doeda-native.json"
PROVENANCE = ROOT / "tests/fixtures/doeda-native-import.json"


def module_text():
    forms = read(FIXTURE)["formations"]
    assert len(forms) == 1570
    assert all(
        (f["base_kind"], f["predicate_class"]) == ("nominal", "verb") for f in forms
    )
    assert [f["head"] for f in forms] == sorted({f["head"] for f in forms})
    rows = "\n".join(f'    ("{f["head"]}", "{f["base"]}"),' for f in forms)
    return (
        "//! Native noun-origin formation proposals, individually sourced in COV-022m.\n"
        "//! Generated by tools/doeda_native_implementation.py; preserve original source evidence.\n"
        "pub(crate) const FORMS: &[(&str, &str)] = &[\n" + rows + "\n];\n"
    )


def generate():
    assert not MODULE.exists() and not LMF.exists() and not PROVENANCE.exists()
    native = read(PREFLIGHT)["complete_native_entries"]
    projected, hashes = project_lmf(native)
    lmf = {"LexicalResource": {"Lexicon": {"LexicalEntry": list(projected.values())}}}
    verify_native_lmf(lmf, native)
    # Compact JSON avoids duplicating the large multilingual source checkpoint.
    LMF.write_text(json.dumps(lmf, ensure_ascii=False, separators=(",", ":")) + "\n")
    MODULE.write_text(module_text())
    PROVENANCE.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "preflight_sha256": sha(PREFLIGHT),
                "fixture_sha256": sha(FIXTURE),
                "lmf_sha256": sha(LMF),
                "source_files_sha256": hashes,
                "native_entries": len(native),
                "projection": "Complete native entries, English translations only; RelatedForm excluded. Full multilingual source closure remains in the immutable native preflight. NIKL Korean Basic Dictionary CC BY-SA 2.0 KR.",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n"
    )
    verify()


def verify():
    provenance = read(PROVENANCE)
    assert provenance["schema_version"] == 1
    assert provenance["preflight_sha256"] == sha(PREFLIGHT)
    assert provenance["fixture_sha256"] == sha(FIXTURE)
    assert provenance["lmf_sha256"] == sha(LMF)
    assert MODULE.read_text() == module_text()
    native = read(PREFLIGHT)["complete_native_entries"]
    assert provenance["native_entries"] == len(native)
    verify_native_lmf(read(LMF), native)
    for path, digest in provenance["source_files_sha256"].items():
        source = ROOT / path
        if source.exists():
            assert sha(source) == digest
    print(
        "Verified 1,570 finite native formation rows and",
        len(native),
        "complete English-projected importer entries.",
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--generate", action="store_true")
    group.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    generate() if args.generate else verify()
