//! Finite native noun/verb semantic links; missing origins remain unknown.
//! Generated by tools/doeda_originless_implementation.py for COV-022m.
use crate::doeda_identity::OriginSource;

pub(crate) fn source(base: &str) -> Option<&'static OriginSource> {
    SOURCES
        .binary_search_by_key(&base, |s| s.base)
        .ok()
        .map(|i| &SOURCES[i])
}

const SOURCES: &[OriginSource] = &[
    OriginSource {
        base: "가늠",
        expected_origins: &[],
        whole_entries: &["krdict:28114"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "갈무리",
        expected_origins: &[],
        whole_entries: &["krdict:14723"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "걱정",
        expected_origins: &[],
        whole_entries: &["krdict:15866"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "근심",
        expected_origins: &[],
        whole_entries: &["krdict:89567"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "되풀이",
        expected_origins: &[],
        whole_entries: &["krdict:14935"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "뒤범벅",
        expected_origins: &[],
        whole_entries: &["krdict:58007"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "뒷받침",
        expected_origins: &[],
        whole_entries: &["krdict:67392"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "뜻풀이",
        expected_origins: &[],
        whole_entries: &["krdict:90948"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "마감",
        expected_origins: &[],
        whole_entries: &["krdict:51505"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "마무리",
        expected_origins: &[],
        whole_entries: &["krdict:53972"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "밑받침",
        expected_origins: &[],
        whole_entries: &["krdict:56783"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "부축",
        expected_origins: &[],
        whole_entries: &["krdict:59625"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "손질",
        expected_origins: &[],
        whole_entries: &["krdict:63897"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "얘기",
        expected_origins: &[],
        whole_entries: &["krdict:67259"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "이야기",
        expected_origins: &[],
        whole_entries: &["krdict:74011"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "풀이",
        expected_origins: &[],
        whole_entries: &["krdict:83643"],
        whole_origins_complete: false,
    },
    OriginSource {
        base: "흥정",
        expected_origins: &[],
        whole_entries: &["krdict:89929"],
        whole_origins_complete: false,
    },
];
